import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const out = join(root, '.generated', 'preview')
await mkdir(out, { recursive: true })
let css = await readFile(join(root, 'src', 'client', 'style.css'), 'utf8')
const embeddedAssets = {
  ASSET_BUTTON_NORMAL: { path: join(root, 'assets', 'generated', 'button-normal.png'), mime: 'image/png' },
  ASSET_BUTTON_HOVER: { path: join(root, 'assets', 'generated', 'button-hover.png'), mime: 'image/png' },
  ASSET_BUTTON_PRESSED: { path: join(root, 'assets', 'generated', 'button-pressed.png'), mime: 'image/png' },
  ASSET_PANEL: { path: join(root, 'assets', 'generated', 'panel.png'), mime: 'image/png' },
  ASSET_TOOLTIP: { path: join(root, 'assets', 'generated', 'tooltip.png'), mime: 'image/png' },
  ASSET_STONE: { path: join(root, 'assets', 'generated', 'stone.png'), mime: 'image/png' },
  ASSET_DEEPSLATE: { path: join(root, 'assets', 'generated', 'deepslate.png'), mime: 'image/png' },
  ASSET_ICONS: { path: join(root, 'assets', 'generated', 'icons.png'), mime: 'image/png' },
  ASSET_FONT_UI: { path: join(root, 'assets', 'fonts', 'fusion-pixel-10px-monospaced-zh-hans.woff2'), mime: 'font/woff2' },
}
for (const [token, asset] of Object.entries(embeddedAssets)) {
  const data = await readFile(asset.path)
  css = css.replaceAll(`__${token}__`, `data:${asset.mime};base64,${data.toString('base64')}`)
}
if (/__ASSET_[A-Z_]+__/.test(css)) throw new Error('Unresolved bundled asset placeholder in preview CSS')
const sprite = (index, size = 24) => `<span class="craft-sprite" style="width:${size}px;height:${size}px;background-position:${-index * size}px 0;background-size:${9 * size}px ${size}px"></span>`
const hotbar = Array.from({ length: 9 }, (_, index) => `<div class="${index === 0 ? 'active' : index === 4 ? 'selected' : ''}"><small>${index + 1}</small>${index === 0 ? `${sprite(0)}<b>EXEC</b>` : index === 4 ? `${sprite(2)}<b>MODEL</b>` : ''}</div>`).join('')
const html = `<!doctype html><html><head><meta charset="utf-8"><style>
${css}
html,body{margin:0;width:100%;height:100%;overflow:hidden;background:#101410;color:#e7e7df}body{--dsw-alias-bg-base:#111611}.preview-app{height:100vh;display:grid;grid-template-columns:238px 1fr}.preview-sidebar{padding:14px;background:rgba(11,14,11,.94);border-right:3px solid #060806}.brand{display:flex;align-items:center;gap:10px;padding:8px 7px 18px;color:#8ddd61;font-size:16px}.world{margin:5px 0;padding:9px;color:#dbd8ca;background:#242a23;border:2px solid #070807;box-shadow:inset 2px 2px #4d574b}.world small{display:block;margin-top:4px;color:#7f8b7b;font-size:8px}.session{margin-top:14px;color:#9aa197;font-size:9px}.session div{margin-top:6px;padding:8px;border-left:3px solid #67bd45;background:#1b211a;color:#eee}.preview-main{position:relative;display:flex;flex-direction:column;min-width:0;background:linear-gradient(rgba(12,16,13,.89),rgba(12,16,13,.89)),var(--craft-world-texture)}.preview-header{height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 22px;border-bottom:2px solid #050705;background:rgba(16,21,17,.94)}.preview-header h1{margin:0;font-size:14px}.preview-header span{font-size:8px;color:#8b9688}.chat{flex:1;overflow:hidden;padding:24px max(30px,8vw) 145px}.message{max-width:760px;margin:0 auto 18px;padding:13px 16px;line-height:1.65;font-size:11px;background:#181e18;border:2px solid #080a08;box-shadow:inset 2px 2px #3d463c}.message.user{margin-right:0;background:#293626;border-color:#10170e}.toolcard{display:flex;align-items:center;gap:9px;margin-top:10px;padding:10px;color:#c8d4c3;background:#0e120e;border:2px solid #384137}.toolcard small{color:#78c852}.composer{position:absolute;left:50%;bottom:88px;transform:translateX(-50%);width:min(760px,68vw);padding:12px 14px;background:#171b17;border:3px solid;border-color:#788078 #171a17 #171a17 #788078;box-shadow:0 5px 0 rgba(0,0,0,.35)}.composer span{font-size:10px;color:#7e887c}.composer button{float:right;padding:6px 13px;color:#fff;background:#4e7c3b;border:2px solid #96c779}
</style></head><body class="craft-ui-enabled craft-atmosphere" data-craft-theme="craft-deepslate" data-craft-motion="full"><div class="preview-app"><aside class="preview-sidebar"><div class="brand">${sprite(8,28)}<b>DSH CRAFT UI</b></div><div class="world"><b>DeepSeek Harness</b><small>OVERWORLD · LOCAL WORKSPACE</small></div><div class="session">RECENT QUESTS<div>◆ Build Minecraft UI plugin</div><div style="border-left-color:#596059;color:#92988f">◇ Research resource packs</div></div></aside><main class="preview-main"><header class="preview-header"><h1>Build Minecraft UI plugin</h1><span>DEEPSLATE NIGHT · HIGH REASONING</span></header><section class="chat"><div class="message user">把 DeepSeek Harness 做成最顶级、最还原的 Minecraft 工作界面。</div><div class="message"><b>正在完成本地资源包导入与 Harness 玩法映射。</b><div class="toolcard">${sprite(0,26)}<div><b>exec_command</b><br><small>RUNNING · RESOURCE IMPORT TESTS</small></div></div></div></section><div class="composer"><span>输入消息，或使用 / 命令…</span><button>发送</button></div><div class="craft-overlay"><div class="craft-particles">${Array.from({length:12},(_,i)=>`<i style="left:${(i*37+11)%100}%;animation-delay:${(i*.43)%3.4}s"></i>`).join('')}</div><div class="craft-boss craft-boss-active"><b>Ship the complete DSH Craft UI plugin</b><span><i style="width:62%"></i></span><small>ACTIVE · ROUND 8/13</small></div><div class="craft-equipment craft-enchanted">${sprite(7,32)}<span><small>DEEPSEEK</small><b>deepseek-reasoner</b><em>✦ high enchantment</em></span></div><div class="craft-player-list"><header>${sprite(3,20)} COMPANIONS</header><div><i class="online"></i><span>Resource worker</span><small>WORKING</small></div><div><i></i><span>Visual QA</span><small>IDLE</small></div></div><div class="craft-quest"><header>${sprite(1,22)} QUEST LOG</header><b>Connect official resource sprites</b><span>5/8 COMPLETE · PLAN MODE</span></div><div class="craft-hotbar">${hotbar}</div><div class="craft-xp craft-xp-warn" title="Context 96000 / 128000 tokens"><b>5</b><span><i style="width:75%"></i></span><small>CONTEXT 75%</small></div><div class="craft-tool-toast">${sprite(0,32)}<span><b>verify package</b><small>另有 1 个工具运行中</small></span></div></div></main></div></body></html>`
await writeFile(join(out, 'index.html'), html)
console.log(join(out, 'index.html'))
