export const DAY_THEME = {
  id: 'craft-day',
  colorScheme: 'light' as const,
  tokens: {
    '--dsw-alias-bg-base': '#c9c7bd',
    '--dsw-alias-bg-layer-1': '#dedbd0',
    '--dsw-alias-bg-layer-2': '#b9b6aa',
    '--dsw-alias-bg-layer-3': '#a6a397',
    '--dsw-alias-bg-overlay': '#d5d1c4',
    '--dsw-alias-border-l1': '#77756e',
    '--dsw-alias-border-l2': '#5a5954',
    '--dsw-alias-border-l3': '#353532',
    '--dsw-alias-brand-primary': '#4f9b35',
    '--dsw-alias-brand-primary-invert': '#2e6721',
    '--dsw-alias-label-primary': '#26251f',
    '--dsw-alias-label-secondary': '#4c4a40',
    '--dsw-alias-label-caption': '#6e6a5c',
    '--dsw-alias-interactive-bg-hover': '#e9e5d7',
    '--dsw-alias-interactive-bg-active': '#a4c28d',
    '--dsw-specific-sidebar-fill': '#aba89d',
    '--dsw-specific-input-major': '#ebe8dc',
    '--dsw-specific-bubble': '#cadbb9',
    '--dsw-alias-state-success-primary': '#4f9b35',
    '--dsw-alias-state-warn-primary': '#d39a2f',
    '--dsw-alias-state-error-primary': '#c7483d',
  },
}

export const DEEPSLATE_THEME = {
  id: 'craft-deepslate',
  colorScheme: 'dark' as const,
  tokens: {
    '--dsw-alias-bg-base': '#111512',
    '--dsw-alias-bg-layer-1': '#1b201c',
    '--dsw-alias-bg-layer-2': '#252a25',
    '--dsw-alias-bg-layer-3': '#303630',
    '--dsw-alias-bg-overlay': '#20251f',
    '--dsw-alias-border-l1': '#414941',
    '--dsw-alias-border-l2': '#596259',
    '--dsw-alias-border-l3': '#798279',
    '--dsw-alias-brand-primary': '#77c54c',
    '--dsw-alias-brand-primary-invert': '#315a25',
    '--dsw-alias-label-primary': '#f0edda',
    '--dsw-alias-label-secondary': '#c0bda9',
    '--dsw-alias-label-caption': '#8d8b7d',
    '--dsw-alias-interactive-bg-hover': '#313a2e',
    '--dsw-alias-interactive-bg-active': '#43583a',
    '--dsw-specific-sidebar-fill': '#171b18',
    '--dsw-specific-input-major': '#10130f',
    '--dsw-specific-bubble': '#273620',
    '--dsw-alias-state-success-primary': '#77c54c',
    '--dsw-alias-state-warn-primary': '#e2b547',
    '--dsw-alias-state-error-primary': '#ef6657',
  },
}
